services:
  postgres-compose:
    container_name: postgres-container-jobnest
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jobnest-db
    networks:
      - jobnest-network

  rabbitmq-compose:
    container_name: rabbitmq-container-jobnest
    image: rabbitmq:4.1.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - jobnest-network

  redis-compose:
    container_name: redis-container-jobnest
    image: redis:8.4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - jobnest-network

networks:
  jobnest-network:
    driver: bridge