services:
  postgres-compose:
    container_name: postgres-container-jobnest
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jobnest-db
    networks:
      - jobnest-network

networks:
  jobnest-network:
    driver: bridge