services:
  postgres:
    container_name: postgres-container-jobnest
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  rabbitmq:
    container_name: rabbitmq-container-jobnest
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  redis:
    container_name: redis-container-jobnest
    image: redis
    ports:
      - "6379:6379"